/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Craft } from './types';

export const CRAFTS: Craft[] = [
  {
    id: 'electrical',
    name: 'Electrical Wiring',
    nameAr: 'الكهرباء المعمارية',
    nameFr: 'Électricité Bâtiment',
    description: 'Installation and maintenance of electrical systems in buildings.',
    descriptionAr: 'تركيب وصيانة النظم الكهربائية في المباني والمنشآت.',
    descriptionFr: 'Installation et maintenance des systèmes électriques dans les bâtiments.',
    icon: 'Zap',
    tools: ['Multimeter', 'Wire Strippers', 'Conduit Bender', 'Voltage Tester'],
    opportunities: ['Residential Electrician', 'Industrial Technician', 'Maintenance Agent'],
    level: 'secondary',
  },
  {
    id: 'mechanics',
    name: 'Mechanics',
    nameAr: 'الميكانيك',
    nameFr: 'Mécanique Automobile',
    description: 'Maintenance and repair of automotive machinery and engines.',
    descriptionAr: 'صيانة وإصلاح المحركات والآلات الميكانيكية للسيارات.',
    descriptionFr: 'Maintenance et réparation de machines automobiles et de moteurs.',
    icon: 'Wrench',
    tools: ['Socket Set', 'Torque Wrench', 'Diagnostic Scanner', 'Jack Stands'],
    opportunities: ['Auto Mechanic', 'Maintenance Technician', 'Service Advisor'],
    level: 'secondary',
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    nameAr: 'النجارة',
    nameFr: 'Menuiserie',
    description: 'Precision woodworking and structural construction.',
    descriptionAr: 'تشكيل الخشب وصناعة الأثاث والهياكل بدقة واحترافية.',
    descriptionFr: 'Travail du bois de précision et construction de structures.',
    icon: 'Hammer',
    tools: ['Table Saw', 'Chisels', 'Spirit Level', 'Router'],
    opportunities: ['Furniture Maker', 'Construction Carpenter', 'Interior Joiner'],
    level: 'primary',
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    nameAr: 'السباكة',
    nameFr: 'Plomberie',
    description: 'Management of water, gas, and drainage systems.',
    descriptionAr: 'تركيب وإصلاح شبكات المياه والغاز وأنظمة الصرف الصحي.',
    descriptionFr: 'Gestion des systèmes d\'eau, de gaz et de drainage.',
    icon: 'Droplets',
    tools: ['Pipe Wrench', 'Plunger', 'PEX Crimp Tool', 'Tube Cutter'],
    opportunities: ['Sanitary Technician', 'Maintenance Plumber', 'Pipefitter'],
    level: 'primary',
  },
  {
    id: 'welding',
    name: 'Welding',
    nameAr: 'اللحام',
    nameFr: 'Soudure',
    description: 'Joining metals using advanced thermal techniques.',
    descriptionAr: 'ربط المعادن باستخدام الحرارة العالية وتقنيات اللحام المتطورة.',
    descriptionFr: 'Assemblage de métaux utilisant des techniques thermiques avancées.',
    icon: 'Flame',
    tools: ['Welding Mask', 'MIG/TIG Welder', 'Angle Grinder', 'C-Clamps'],
    opportunities: ['Industrial Welder', 'Steel Fabricator', 'Shipyard Welder'],
    level: 'secondary',
  },
  {
    id: 'hvac',
    name: 'HVAC',
    nameAr: 'التبريد والتكييف',
    nameFr: 'Froid et Climatisation',
    description: 'Advanced climate control systems maintenance.',
    descriptionAr: 'صيانة وأنظمة التحكم في المناخ والتهوية والتبريد.',
    descriptionFr: 'Maintenance des systèmes de climatisation avancés.',
    icon: 'Wind',
    tools: ['Manifold Gauge', 'Vacuum Pump', 'Thermometer', 'Leak Detector'],
    opportunities: ['HVAC Technician', 'Installation Expert', 'Systems Designer'],
    level: 'secondary',
  },
  {
    id: 'painting',
    name: 'Painting',
    nameAr: 'الطلاء',
    nameFr: 'Peinture Bâtiment',
    description: 'Decorative and protective surface coatings.',
    descriptionAr: 'تجهيز الأسطح وتطبيق الدهانات الديكورية والواقية.',
    descriptionFr: 'Revêtements de surface décoratifs et protecteurs.',
    icon: 'Paintbrush',
    tools: ['Airless Sprayer', 'Rollers', 'Scrapers', 'Sander'],
    opportunities: ['Interior Decorator', 'Coating Specialist', 'Refurbishment Pro'],
    level: 'primary',
  },
  {
    id: 'barbering',
    name: 'Barbering',
    nameAr: 'الحلاقة',
    nameFr: 'Coiffure Homme',
    description: 'Professional grooming and hair styling arts.',
    descriptionAr: 'فنون العناية بالمظهر وقص الشعر وتصفيفه للرجال.',
    descriptionFr: 'Soins professionnels et arts du coiffage des cheveux.',
    icon: 'Scissors',
    tools: ['Clippers', 'Straight Razor', 'Combs', 'Shears'],
    opportunities: ['Barbershop Owner', 'Style Consultant', 'Professional Stylist'],
    level: 'primary',
  },
  {
    id: 'cooking',
    name: 'Cooking',
    nameAr: 'الطبخ',
    nameFr: 'Cuisine',
    description: 'Professional culinary preparation and presentation.',
    descriptionAr: 'تحضير وتقديم الأطباق والوجبات باحترافية عالية.',
    descriptionFr: 'Préparation et présentation culinaire professionnelle.',
    icon: 'Utensils',
    tools: ["Chef's Knife", 'Mandoline', 'Whisk', 'Pressure Cooker'],
    opportunities: ['Restaurant Chef', 'Catering Manager', 'Food Stylist'],
    level: 'primary',
  },
  {
    id: 'graphic-design',
    name: 'Graphic Design',
    nameAr: 'تصميم الجرافيك',
    nameFr: 'Graphisme',
    description: 'Visual communication and branding through design.',
    descriptionAr: 'التواصل البصري وبناء الهويات التجارية عبر التصميم.',
    descriptionFr: 'Communication visuelle et image de marque par le design.',
    icon: 'Palette',
    tools: ['Graphics Tablet', 'Color Calibrator', 'Design Suite', 'Sketchbook'],
    opportunities: ['UI Designer', 'Brand Strategist', 'Content Creator'],
    level: 'higher',
  },
];
