/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Craft } from './types';

export const CRAFTS: Craft[] = [
  {
    id: 'electrical',
    name: 'Electrical Wiring',
    nameAr: 'الكهرباء المعمارية',
    nameFr: 'Électricité Bâtiment',
    description: 'Installation and maintenance of electrical systems in buildings.',
    descriptionAr: 'تركيب وصيانة النظم الكهربائية في المباني والمنشآت.',
    descriptionFr: 'Installation et maintenance des systèmes électriques dans les bâtiments.',
    icon: 'Zap',
    tools: ['Multimeter', 'Wire Strippers', 'Conduit Bender', 'Voltage Tester'],
    opportunities: ['Residential Electrician', 'Industrial Technician', 'Maintenance Agent'],
    level: 'secondary',
    salary: '$30,000 - $65,000',
    duration: '12 Months',
    skills: ['Circuit Design', 'Safety Protocols', 'Blueprint Reading'],
    difficulty: 'medium',
  },
  {
    id: 'mechanics',
    name: 'Mechanics',
    nameAr: 'الميكانيك',
    nameFr: 'Mécanique Automobile',
    description: 'Maintenance and repair of automotive machinery and engines.',
    descriptionAr: 'صيانة وإصلاح المحركات والآلات الميكانيكية للسيارات.',
    descriptionFr: 'Maintenance et réparation de machines automobiles et de moteurs.',
    icon: 'Wrench',
    tools: ['Socket Set', 'Torque Wrench', 'Diagnostic Scanner', 'Jack Stands'],
    opportunities: ['Auto Mechanic', 'Maintenance Technician', 'Service Advisor'],
    level: 'secondary',
    salary: '$35,000 - $70,000',
    duration: '18 Months',
    skills: ['Engine Diagnostics', 'Hydraulic Systems', 'Brake Systems'],
    difficulty: 'hard',
  },
  {
    id: 'carpentry',
    name: 'Carpentry',
    nameAr: 'النجارة',
    nameFr: 'Menuiserie',
    description: 'Precision woodworking and structural construction.',
    descriptionAr: 'تشكيل الخشب وصناعة الأثاث والهياكل بدقة واحترافية.',
    descriptionFr: 'Travail du bois de précision et construction de structures.',
    icon: 'Hammer',
    tools: ['Table Saw', 'Chisels', 'Spirit Level', 'Router'],
    opportunities: ['Furniture Maker', 'Construction Carpenter', 'Interior Joiner'],
    level: 'primary',
    salary: '$25,000 - $55,000',
    duration: '9 Months',
    skills: ['Joinery', 'Wood Finishing', 'Structural Framing'],
    difficulty: 'medium',
  },
  {
    id: 'plumbing',
    name: 'Plumbing',
    nameAr: 'السباكة',
    nameFr: 'Plomberie',
    description: 'Management of water, gas, and drainage systems.',
    descriptionAr: 'تركيب وإصلاح شبكات المياه والغاز وأنظمة الصرف الصحي.',
    descriptionFr: 'Gestion des systèmes d\'eau, de gaz et de drainage.',
    icon: 'Droplets',
    tools: ['Pipe Wrench', 'Plunger', 'PEX Crimp Tool', 'Tube Cutter'],
    opportunities: ['Sanitary Technician', 'Maintenance Plumber', 'Pipefitter'],
    level: 'primary',
    salary: '$28,000 - $60,000',
    duration: '10 Months',
    skills: ['Pipe Fitting', 'Waste Management', 'System Testing'],
    difficulty: 'medium',
  },
  {
    id: 'welding',
    name: 'Welding',
    nameAr: 'اللحام',
    nameFr: 'Soudure',
    description: 'Joining metals using advanced thermal techniques.',
    descriptionAr: 'ربط المعادن باستخدام الحرارة العالية وتقنيات اللحام المتطورة.',
    descriptionFr: 'Assemblage de métaux utilisant des techniques thermiques avancées.',
    icon: 'Flame',
    tools: ['Welding Mask', 'MIG/TIG Welder', 'Angle Grinder', 'C-Clamps'],
    opportunities: ['Industrial Welder', 'Steel Fabricator', 'Shipyard Welder'],
    level: 'secondary',
    salary: '$32,000 - $68,000',
    duration: '12 Months',
    skills: ['TIG/MIG Welding', 'Metallurgy', 'Metal Cutting'],
    difficulty: 'hard',
  },
  {
    id: 'hvac',
    name: 'HVAC',
    nameAr: 'التبريد والتكييف',
    nameFr: 'Froid et Climatisation',
    description: 'Advanced climate control systems maintenance.',
    descriptionAr: 'صيانة وأنظمة التحكم في المناخ والتهوية والتبريد.',
    descriptionFr: 'Maintenance des systèmes de climatisation avancés.',
    icon: 'Wind',
    tools: ['Manifold Gauge', 'Vacuum Pump', 'Thermometer', 'Leak Detector'],
    opportunities: ['HVAC Technician', 'Installation Expert', 'Systems Designer'],
    level: 'secondary',
    salary: '$34,000 - $72,000',
    duration: '15 Months',
    skills: ['Thermodynamics', 'Refrigerant Handling', 'Electric Controls'],
    difficulty: 'hard',
  },
  {
    id: 'painting',
    name: 'Painting',
    nameAr: 'الطلاء',
    nameFr: 'Peinture Bâtiment',
    description: 'Decorative and protective surface coatings.',
    descriptionAr: 'تجهيز الأسطح وتطبيق الدهانات الديكورية والواقية.',
    descriptionFr: 'Revêtements de surface décoratifs et protecteurs.',
    icon: 'Paintbrush',
    tools: ['Airless Sprayer', 'Rollers', 'Scrapers', 'Sander'],
    opportunities: ['Interior Decorator', 'Coating Specialist', 'Refurbishment Pro'],
    level: 'primary',
    salary: '$20,000 - $45,000',
    duration: '6 Months',
    skills: ['Color Matching', 'Surface Preparation', 'Faux Finishing'],
    difficulty: 'easy',
  },
  {
    id: 'barbering',
    name: 'Barbering',
    nameAr: 'الحلاقة',
    nameFr: 'Coiffure Homme',
    description: 'Professional grooming and hair styling arts.',
    descriptionAr: 'فنون العناية بالمظهر وقص الشعر وتصفيفه للرجال.',
    descriptionFr: 'Soins professionnels et arts du coiffage des cheveux.',
    icon: 'Scissors',
    tools: ['Clippers', 'Straight Razor', 'Combs', 'Shears'],
    opportunities: ['Barbershop Owner', 'Style Consultant', 'Professional Stylist'],
    level: 'primary',
    salary: '$22,000 - $50,000',
    duration: '8 Months',
    skills: ['Hair Cutting', 'Shaving Techniques', 'Customer Service'],
    difficulty: 'easy',
  },
  {
    id: 'cooking',
    name: 'Cooking',
    nameAr: 'الطبخ',
    nameFr: 'Cuisine',
    description: 'Professional culinary preparation and presentation.',
    descriptionAr: 'تحضير وتقديم الأطباق والوجبات باحترافية عالية.',
    descriptionFr: 'Préparation et présentation culinaire professionnelle.',
    icon: 'Utensils',
    tools: ["Chef's Knife", 'Mandoline', 'Whisk', 'Pressure Cooker'],
    opportunities: ['Restaurant Chef', 'Catering Manager', 'Food Stylist'],
    level: 'primary',
    salary: '$24,000 - $58,000',
    duration: '10 Months',
    skills: ['Knife Skills', 'Food Safety', 'Menu Planning'],
    difficulty: 'medium',
  },
  {
    id: 'graphic-design',
    name: 'Graphic Design',
    nameAr: 'تصميم الجرافيك',
    nameFr: 'Graphisme',
    description: 'Visual communication and branding through design.',
    descriptionAr: 'التواصل البصري وبناء الهويات التجارية عبر التصميم.',
    descriptionFr: 'Communication visuelle et image de marque par le design.',
    icon: 'Palette',
    tools: ['Graphics Tablet', 'Color Calibrator', 'Design Suite', 'Sketchbook'],
    opportunities: ['UI Designer', 'Brand Strategist', 'Content Creator'],
    level: 'higher',
    salary: '$40,000 - $85,000',
    duration: '24 Months',
    skills: ['Typography', 'Adobe Creative Suite', 'UX Principles'],
    difficulty: 'medium',
  },
];
